[project]
name = "task-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "VN-78", email = "vishwanath.s.god@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic>=2.13.4",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
task-manager = "task_manager:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
